services:
    nginx:
        container_name: ${CONTAINER_NAME}-nginx
        image: nginx:latest
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        restart: unless-stopped 
        env_file: .env 
        ports:
            - "8080:80"
            - "443:443"

        volumes:
            - ./nginx.conf:/etc/nginx/conf.d:rw
    database:
        container_name: ${CONTAINER_NAME}-database
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
        env_file: .env
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - internal

    php_myadmin:
        container_name: ${CONTAINER_NAME}-phpmyadmin
        image: phpmyadmin:latest
        restart: unless-stopped
        env_file: .env
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DATABASE_USER}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - internal
    wordpress:
        depends_on:
          - database
        container_name: ${CONTAINER_NAME}-wordpress
        image: wordpress:6.5.2-fpm-alpine
        restart: unless-stopped
        env_file: .env
        environment:
          WORDPRESS_DB_HOST: database:3306 # use the same name as database service
          WORDPRESS_DB_NAME: ${DATABASE_NAME}
          WORDPRESS_DB_USER: ${DATABASE_USER}
          WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
          - wordpress:/var/www/html
          - ./src:/var/www/html/wp-content:rw
        networks:
          - internal
volumes:
    dbdata:
        driver: local
    wordpress:
        driver: local
networks:
    internal:
        driver: bridge
    
          
        
